micronaut:
  application:
    name: micronaut-simple-api

endpoints:
  info:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  health:
    details-visible: ANONYMOUS
    disk-space:
      enabled: true
