spring:
  application:
    name: springboot-simple-api
  main:
    banner-mode: "off"

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: info, health, beans, metrics, env
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true
