micronaut:
  application:
    name: micronaut-elasticsearch

endpoints:
  info:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  health:
    details-visible: ANONYMOUS
    disk-space:
      enabled: true

elasticsearch:
  httpHosts: http://${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_REST_PORT:9200}
  indexes:
    movies: micronaut.movies

jackson:
  serializationInclusion: ALWAYS # Include empty arrays in JSON output