micronaut:
  application:
    name: producer-api
  metrics:
    enabled: true
    binders:
      kafka:
        enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

endpoints:
  info:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  health:
    details-visible: ANONYMOUS
    disk-space:
      enabled: true
    jdbc:
      enabled: true

kafka:
  bootstrap:
    servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}

app:
  kafka:
    output:
      topic: micronaut.news.json
