spring:
  application:
    name: springboot-book-api
  main:
    banner-mode: "off"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/bookdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: secret

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: info, health, beans, metrics, env
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true
