spring:
  application:
    name: springboot-book-api
  main:
    banner-mode: "off"
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/bookdb?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: secret
    initialization-mode: never

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: info, health, beans, metrics, env
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
    metrics:
      enabled: true
    env:
      enabled: true
